services:
  - type: web
    name: seo-api
    env: node
    rootDir: apps/api
    plan: free
    buildCommand: |
      npm install
    startCommand: npm run start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: seo-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: seo-redis
          type: redis
          property: connectionString
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 4000

  - type: web
    name: seo-frontend
    env: node
    rootDir: apps/web
    plan: free
    buildCommand: |
      npm install
      npm run build
    startCommand: npm run start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        fromService:
          name: seo-api
          type: web
          property: url

databases:
  - name: seo-db
    plan: free

redis:
  - name: seo-redis
    plan: free
